---
title: "Gewichtung mit R"
author:  "Dr. Uwe Remer"
subtitle: "Grundlagen und Umsetzung"
date: 2023-08-17
affiliation: "Universität Stutgart, CSS-Lab"
---

# Gewichtung in R

Dies ist das Skript zur *Videoserie Gewichtung in R*, die für die Stelle "Quantitative Methoden" der [FernUni Hagen](https://www.fernuni-hagen.de/) entstanden ist.

Diese Videoserie besteht aus sechs aufeinander aufbauenden Teilen:

-   Teil 1: Was ist Gewichtung?
-   Teil 2: Warum gewichten wir?
-   Teil 3: Wo finden wir Gewichte in bekannten Surveys?
-   Teil 4: Wie nutzen wir einfache Gewichte R? Das `sjmisc` und `weights` Paket
-   Teil 5: Wie nutzen wir einfache Gewichte in R? Das `survey` Paket
-   Teil 6: Wie gewichten wir komplexe Stichproben in R?

Zu allen Videos gibt es auf dieser Seite den R Code, sowie das Skript.

## Voraussetzungen

Damit Sie den Inhalten folgen können, sollten Sie über Grundlagen in sozialwissenschaftlichen Methoden wie Datenerhebung und Stichprobenziehung verfügen. Außerdem sollten Sie Kenntnisse in Statistik haben, also wissen, was Mittelwerte und Streuungsmaße sind und was eine lineare Regression ist. Darüber hinaus werden Grundlagen in R vorausgesetzt.

## Zielgruppe

BA oder MA Studierende aus Wirtschafts- und Sozialwissenschaften, Psychologie oder Digital Humanities, und alle, die mit Umfragedaten oder generell mit stichprobenbasierten Daten arbeiten.

# Literatur zum Einstieg

-   Manderscheid, K., 2017. Sozialwissenschaftliche Datenanalyse mit R. Springer Fachmedien Wiesbaden, Wiesbaden. Kap. 11, S. 225-238. <https://doi.org/10.1007/978-3-658-15902-3>
-   Gabler, S., Ganninger, M., 2010. Gewichtung, in: Wolf, C., Best, H. (Hrsg..), Handbuch der sozialwissenschaftlichen Datenanalyse. VS Verlag für Sozialwissenschaften, Wiesbaden, S. 143--164. <https://doi.org/10.1007/978-3-531-92038-2_7>
